sudo: false # http://docs.travis-ci.com/user/workers/container-based-infrastructure/
language: node_js
node_js:
  - 0.12
  - 4
  - 6
  - 7
  - 14

arch:
  - amd64
  - ppc64le
  
jobs:
  exclude:
    - arch: ppc64le
      node_js: "0.12"

notifications:
  email:
    - medikoo+es6-map@medikoo.com

script: "npm test && npm run lint"
